# Generated by Django 3.1.5 on 2021-03-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0003_auto_20210308_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=models.URLField(default='https://cdn.shopify.com/s/files/1/1132/3108/files/NZ_corner_400x.jpg?v=1603743748'),
        ),
    ]
