# Generated by Django 3.1.5 on 2021-03-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0004_auto_20210308_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='image_destionation',
            new_name='image_destination',
        ),
    ]
