# Generated by Django 3.1.5 on 2021-03-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0005_auto_20210308_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='image_destination',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image_event',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='image_food',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image_profile',
            new_name='image',
        ),
    ]
