# Generated by Django 3.1.5 on 2021-03-24 12:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0010_auto_20210324_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
