# Generated by Django 3.1.5 on 2021-03-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0012_auto_20210324_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
