# Generated by Django 3.1.5 on 2021-03-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0013_remove_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='body',
        ),
    ]
