# Generated by Django 3.1.5 on 2021-03-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0015_auto_20210326_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='body',
        ),
    ]
