# Generated by Django 3.1.5 on 2021-03-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0018_auto_20210327_0336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='image_url',
        ),
    ]
