# Generated by Django 3.1.5 on 2021-03-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0020_auto_20210327_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='image_url',
        ),
    ]
