# Generated by Django 3.1.5 on 2021-03-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0021_auto_20210327_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='short_description',
            field=models.CharField(default='Short description', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='CS50 Web Final Project', max_length=280),
        ),
    ]
