# Generated by Django 3.1.5 on 2021-03-28 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit_komodo', '0022_auto_20210328_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='blog_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='destination',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='destination_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='event_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='food',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='food_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
